services:
  api:
    build: .
    container_name: server_fastAPI
    ports: 
      - "5000:5000"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload